{
  "uid" : "16c28aeee10283fe",
  "name" : "can run runs.main and runs.post end-to-end",
  "fullName" : "GitHub Actions Test.can run runs.main and runs.post end-to-end",
  "historyId" : "aab39a24d41767fdf2f98931deb32f7",
  "time" : {
    "start" : 1580807480489,
    "stop" : 1580807480581,
    "duration" : 92
  },
  "description" : "",
  "descriptionHtml" : "",
  "status" : "failed",
  "statusMessage" : "Error: expect(received).toBe(expected) // Object.is equality\n                \n                - Expected  -  2\n                + Received  + 13\n                \n                - stdout > ::debug::Reading inputs\n                - stdout > ::debug::Cloned: undefined\n                + stderr > (node:3891) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'setFailed' of undefined\n                +     at /home/runner/work/github-action-working-directory/github-action-working-directory/dist/src/clone.ts:28:1\n                +     at Generator.next (<anonymous>)\n                +     at /home/runner/work/github-action-working-directory/github-action-working-directory/dist/src/clone.ts:8:1\n                +     at new Promise (<anonymous>)\n                +     at module.exports.985.__awaiter (/home/runner/work/github-action-working-directory/github-action-working-directory/dist/src/clone.ts:4:1)\n                +     at run (/home/runner/work/github-action-working-directory/github-action-working-directory/dist/src/clone.ts:20:1)\n                +     at Object.985 (/home/runner/work/github-action-working-directory/github-action-working-directory/dist/src/clone.ts:32:1)\n                +     at __webpack_require__ (/webpack/bootstrap:19:1)\n                +     at startup (/webpack/bootstrap:34:1)\n                +     at /webpack/bootstrap:38:1\n                + stderr > (node:3891) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)\n                + stderr > (node:3891) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.\n                  ↵",
  "statusTrace" : "Error: expect(received).toBe(expected) // Object.is equality\n                \n                - Expected  -  2\n                + Received  + 13\n                \n                - stdout > ::debug::Reading inputs\n                - stdout > ::debug::Cloned: undefined\n                + stderr > (node:3891) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'setFailed' of undefined\n                +     at /home/runner/work/github-action-working-directory/github-action-working-directory/dist/src/clone.ts:28:1\n                +     at Generator.next (<anonymous>)\n                +     at /home/runner/work/github-action-working-directory/github-action-working-directory/dist/src/clone.ts:8:1\n                +     at new Promise (<anonymous>)\n                +     at module.exports.985.__awaiter (/home/runner/work/github-action-working-directory/github-action-working-directory/dist/src/clone.ts:4:1)\n                +     at run (/home/runner/work/github-action-working-directory/github-action-working-directory/dist/src/clone.ts:20:1)\n                +     at Object.985 (/home/runner/work/github-action-working-directory/github-action-working-directory/dist/src/clone.ts:32:1)\n                +     at __webpack_require__ (/webpack/bootstrap:19:1)\n                +     at startup (/webpack/bootstrap:34:1)\n                +     at /webpack/bootstrap:38:1\n                + stderr > (node:3891) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)\n                + stderr > (node:3891) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.\n                  ↵\n                    at /home/runner/work/github-action-working-directory/github-action-working-directory/tests/end-to-end.github-action.ts:98:24\n                    at Generator.next (<anonymous>)\n                    at fulfilled (/home/runner/work/github-action-working-directory/github-action-working-directory/tests/end-to-end.github-action.ts:5:58)\n                    at processTicksAndRejections (internal/process/task_queues.js:94:5)",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ ],
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "suite",
    "value" : "GitHub Actions Test"
  }, {
    "name" : "testClass",
    "value" : "GitHub Actions Test"
  }, {
    "name" : "testMethod",
    "value" : "can run runs.main and runs.post end-to-end"
  }, {
    "name" : "package",
    "value" : "GitHub Actions Test"
  }, {
    "name" : "resultFormat",
    "value" : "allure1"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ {
      "name" : "Product defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "tags" : [ ]
  },
  "source" : "16c28aeee10283fe.json",
  "parameterValues" : [ ]
}